# Generated by Django 3.2.9 on 2021-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='user phone'),
            preserve_default=False,
        ),
    ]
