version: "3.9"

services:
  backend:
#    command: python ./app/manage.py runserver 0.0.0.0:8000
    image: local
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/project/code"
    ports:
      - "8000:8000"
      - "8001:8001"  #debug_port
    depends_on:
      - postgres
      - rabbitmq
      - memcached

  celery:
    command: celery -A settings worker -l info --pool threads -c 10
    image: local
    build: .
    container_name: celery
    depends_on:
      - postgres
      - rabbitmq
      - memcached

  celerybeat:
    command: celery -A settings beat -l info
    image: local
    build: .
    container_name: celerybeat
    depends_on:
      - postgres
      - rabbitmq
      - memcached
      - celery

  flower:
    command: celery -A settings flower
    image: local
    build: .
    container_name: flower
    ports:
      - "5555:5555"
    env_file: .env
    depends_on:
      - backend
      - rabbitmq
      - celery
      - celerybeat

  memcached:
    image: memcached:1.6.12
    container_name: memcached
#    ports:
#      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    env_file: .env
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file: .env
#    ports:
#      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - "5050:80"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_data: {}