# Generated by Django 3.2.7 on 2021-11-21 12:02

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.avatar_upload_to),
        ),
    ]
