# Generated by Django 3.2.7 on 2021-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')], default=1),
        ),
    ]
