# Generated by Django 3.2.7 on 2021-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
