# Generated by Django 3.2.7 on 2021-10-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
