# Generated by Django 3.2.7 on 2021-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='email_from',
            new_name='reply_to',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message',
        ),
        migrations.AddField(
            model_name='contactus',
            name='body',
            field=models.CharField(default='default', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='raw_content',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro'), (3, 'Hryvnia')], default=1),
        ),
    ]
