# Generated by Django 3.2.7 on 2021-12-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
