# Generated by Django 3.2.7 on 2021-10-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='created',
        ),
    ]
